// +FHDR----------------------------------------------------------------------------
//                 Copyright (c) 2022 
//                       ALL RIGHTS RESERVED
// ---------------------------------------------------------------------------------
// Filename      : tb_rvseed.v
// Author        : Rongye
// Created On    : 2022-03-25 04:18
// Last Modified : 2026-05-26
// ---------------------------------------------------------------------------------
// Description   : Simplified testbench for EasyAXI S01E09
//   - Write transactions are generated by EASYAXI_PROD (triggered by prod_start)
//   - Read transactions are generated by EASYAXI_CONS (triggered by cons_start)
//
// -FHDR----------------------------------------------------------------------------
`timescale 1ns / 1ps

module TESTBENCH ();

reg                  clk;
reg                  rst_n;

// Producer control
reg                  prod_start;
wire                 prod_done;

// Consumer control
reg                  cons_start;
wire                 cons_done;
wire                 cons_error;


localparam SIM_PERIOD = 20; // 20ns -> 50MHz

localparam CONS_CHECK_CQE = 4'd4;  // Consumer state: CHECK_CQE

// CQE re-poll tracking
reg [7:0] re_poll_cnt [0:3];
reg       cons_retry_observed;
integer   rp_i;

// Clock generation
initial begin
    #(SIM_PERIOD/2);
    clk = 1'b0;
    forever #(SIM_PERIOD/2) clk = ~clk;
end

// Timeout
initial begin
    #(SIM_PERIOD * 100000); // 2ms timeout
    $display("SIMULATION TIMEOUT");
    $finish;
end

// Reset task
task reset;
    begin
        rst_n = 0; 
        prod_start = 0;
        cons_start = 0;
        #(SIM_PERIOD * 1);
        rst_n = 1;
        #(SIM_PERIOD * 5 + 1);
    end
endtask

// Main test sequence
initial begin
    $display("EasyAXI S01E09 CQE Test Started");
    
    // Initialize
    prod_start = 0;
    cons_start = 0;
    
    // Reset
    reset;
    #(SIM_PERIOD * 10);
    
    //----------------------------------------------------------
    // Concurrent phase: Producer and Consumer run simultaneously
    // Consumer polls CQEs, waiting for each CQE to become valid
    // before reading the corresponding Data Block
    //----------------------------------------------------------
    $display("=== Concurrent: Producer + Consumer started together ===");

    // Fire both prod_start and cons_start simultaneously
    #(SIM_PERIOD/4);
    prod_start = 1;
    cons_start = 1;
    #(SIM_PERIOD);
    prod_start = 0;
    cons_start = 0;

    // Wait for both to finish
    fork
        begin
            while (!prod_done) @(posedge clk);
            $display("Producer done");
        end
        begin
            while (!cons_done) @(posedge clk);
            $display("Consumer done");
        end
    join

    // Check for errors
    if (cons_error) begin
        $display("Test failed: data mismatch detected");
        $finish;
    end
    $display("Concurrent test passed");
    
    // Report re-poll statistics
    $display("=== CQE Re-Poll Summary ===");
    $display("cons_retry_observed = %0d", cons_retry_observed);
    for (rp_i = 0; rp_i < 4; rp_i = rp_i + 1) begin
        if (re_poll_cnt[rp_i] > 0)
            $display("  idx=%0d: %0d re-polls", rp_i, re_poll_cnt[rp_i]);
    end
    
    #(SIM_PERIOD * 10);
    
    $display("All tests passed!");
    $finish;

end

// DUT instantiation
EASYAXI_TOP #(
    .PROD_NUM_BLOCKS (4),
    .CONS_NUM_BLOCKS (4)
) U_EASYAXI_TOP (
    .clk                            ( clk                           ),
    .rst_n                          ( rst_n                         ),
    
    // Producer control
    .prod_start                     ( prod_start                    ),
    .prod_done                      ( prod_done                     ),
    
    // Consumer control
    .cons_start                     ( cons_start                    ),
    .cons_done                      ( cons_done                     ),
    .cons_error                     ( cons_error                    )
);

//--------------------------------------------------------------------------------
// CQE Re-Poll Monitor — detect when Consumer finds a CQE not yet valid
// Uses Producer's state to determine whether the corresponding CQE has been written
//--------------------------------------------------------------------------------

always @(posedge clk or negedge rst_n) begin
    if (~rst_n) begin
        for (rp_i = 0; rp_i < 4; rp_i = rp_i + 1)
            re_poll_cnt[rp_i] <= 8'd0;
        cons_retry_observed <= 1'b0;
    end
    else if (U_EASYAXI_TOP.U_EASYAXI_CONS.state_r == CONS_CHECK_CQE) begin
        if (U_EASYAXI_TOP.U_EASYAXI_CONS.cqe_valid) begin
            $display("CQE HIT [idx=%0d]: Producer state=%0d (idx=%0d), retries for this idx=%0d",
                     U_EASYAXI_TOP.U_EASYAXI_CONS.idx_r,
                     U_EASYAXI_TOP.U_EASYAXI_PROD.state_r,
                     U_EASYAXI_TOP.U_EASYAXI_PROD.idx_r,
                     re_poll_cnt[U_EASYAXI_TOP.U_EASYAXI_CONS.idx_r]);
        end else begin
            re_poll_cnt[U_EASYAXI_TOP.U_EASYAXI_CONS.idx_r] <=
                re_poll_cnt[U_EASYAXI_TOP.U_EASYAXI_CONS.idx_r] + 8'd1;
            cons_retry_observed <= 1'b1;
            $display("CQE MISS [idx=%0d]: Producer state=%0d (prod_idx=%0d), retry count=%0d",
                     U_EASYAXI_TOP.U_EASYAXI_CONS.idx_r,
                     U_EASYAXI_TOP.U_EASYAXI_PROD.state_r,
                     U_EASYAXI_TOP.U_EASYAXI_PROD.idx_r,
                     re_poll_cnt[U_EASYAXI_TOP.U_EASYAXI_CONS.idx_r] + 8'd1);
        end
    end
end

// FSDB dump for debugging
initial begin
    $fsdbDumpfile("sim_out.fsdb");
    $fsdbDumpvars("+all");
end

endmodule
