$ROOT_PATH/rtl/easyaxi_define.v
$ROOT_PATH/rtl/easyaxi_top.v
$ROOT_PATH/rtl/easyaxi_mst_rd_ctrl.v
$ROOT_PATH/rtl/easyaxi_slv_rd_ctrl.v
$ROOT_PATH/rtl/easyaxi_mst_wr_ctrl.v
$ROOT_PATH/rtl/easyaxi_slv_wr_ctrl.v
$ROOT_PATH/rtl/easyaxi_arb.v
$ROOT_PATH/rtl/easyaxi_order.v
$ROOT_PATH/rtl/easyaxi_fifo.v
